### PR TITLE
[AR-213] add mltk as an app in splunk deployment

### PR DESCRIPTION
**Pull request by jzsplunk**
Still testing here so far I think I have the apps in the right place on s3 and the proper yml for ansible.

### CODE REVIEW

**Comment by jzsplunk** [comment]
The update is still missing a piece of logic it looks like the apps did not get deployed with this commit.  The error that is being throw in for me is `

Warning: Value for undeclared variable

  on /var/folders/97/wrqppc017dlbtysk672678kr0000gn/T/tmp_phukouq.tfvars.json line 1:
   1: {"key_name": "jzadeh_ssh_key", "ip_whitelist": ["0.0.0.0/0"], "private_key_path": "~/.ssh/id_rsa", "region": "us-west-2", "availability_zone": "us-west-2a", "subnet_cidr": "10.0.0.0/16", "splunk_admin_password": "I-l1ke-Attack-Range!", "splunk_url": "https://www.splunk.com/page/download_track?file=7.3.2/linux/splunk-7.3.2-c60db69f8e32-Linux-x86_64.tgz&ac=&wget=true&name=wget&platform=Linux&architecture=x86_64&version=7.3.2&product=splunk&typed=release", "splunk_binary": "splunk-7.3.2-c60db69f8e32-Linux-x86_64.tgz", "s3_bucket_url": "https://attack-range-appbinaries.s3-us-west-2.amazonaws.com", "splunk_windows_ta": "splunk-add-on-for-microsoft-windows_700.tgz", "splunk_sysmon_ta": "add-on-for-microsoft-sysmon_810.tgz", "splunk_cim_app": "splunk-common-information-model-cim_4130.tgz", "splunk_escu_app": "DA-ESS-ContentUpdate-latest.tar.gz", "splunk_asx_app": "Splunk_Analytic_Story_Execution-latest.tar.gz", "splunk_python_app": "python-for-scientific-computing-for-linux-64-bit_14.tgz", "splunk_mltk_app": "splunk-machine-learning-toolkit_450.tgz", "win_username": "Administrator", "win_password": "I-l1ke-Attack-Range!", "splunk_uf_win_url": "https://www.splunk.com/page/download_track?file=7.3.2/windows/splunkforwarder-7.3.2-c60db69f8e32-x64-release.msi&ac=&wget=true&name=wget&platform=Windows&architecture=x86_64&version=7.3.2&product=universalforwarder&typed=release", "win_sysmon_url": "https://download.sysinternals.com/files/Sysmon.zip", "win_sysmon_template": "SysmonConfig-TSwift.xml", "windows_domain_controller": "1", "windows_server": "0", "kali_machine": "0", "splunk_server_private_ip": "10.0.1.5", "windows_domain_controller_private_ip": "10.0.1.6", "windows_domain_controller_os": "Windows_Server-2016-English-Full-Base-2019.12.16", "windows_server_private_ip": "10.0.1.7", "windows_server_os": "Windows_Server-2016-English-Full-Base-2019.12.16", "windows_server_join_domain": "1", "kali_machine_private_ip": "10.0.1.8"}

The root module does not declare a variable named "splunk_python_app". To use
this value, add a "variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.

(and one more similar warning elsewhere)`

**Comment by jzsplunk** [comment]
After updating the various pointers to the apps I still have not seen the apps populate on the splunk search head I am testing on.  The output in build logs looks better though:

`
module.splunk-server.aws_instance.splunk-server (local-exec): TASK [search_head : Check if python app exists] ********************************
module.splunk-server.aws_instance.splunk-server (local-exec): ok: [52.36.175.216]

module.splunk-server.aws_instance.splunk-server (local-exec): TASK [search_head : download Python app from S3 bucket] ************************
module.splunk-server.aws_instance.splunk-server (local-exec): changed: [52.36.175.216]

module.splunk-server.aws_instance.splunk-server (local-exec): TASK [search_head : Install Python app via REST] *******************************
module.splunk-server.aws_instance.splunk-server (local-exec): ok: [52.36.175.216]

module.splunk-server.aws_instance.splunk-server (local-exec): TASK [search_head : Check if MLTK ta exists] ***********************************
module.splunk-server.aws_instance.splunk-server (local-exec): ok: [52.36.175.216]

module.splunk-server.aws_instance.splunk-server (local-exec): TASK [search_head : download MLTK app from S3 bucket] **************************
module.splunk-server.aws_instance.splunk-server (local-exec): changed: [52.36.175.216]

module.splunk-server.aws_instance.splunk-server (local-exec): TASK [search_head : Install MLTK app via REST] *********************************
module.splunk-server.aws_instance.splunk-server (local-exec): ok: [52.36.175.216]`

**Comment by P4T12ICK** [comment]
I fixed the problems with installation. The download variables were pointing to a wrong variable. The apps are installed properly. Can you please check if further configuration steps are needed to use MLTK.

**Comment by jzsplunk** [comment]
After Patricks last checking (thanks for the fix @P4T12ICK !) the MLTK app is loading by default and able to process MLTK related SPL.   Looks good from the testing on my end can anyone review and merge when they get a chance.

**Pull request merged**
