### PR TITLE
Current fixes for successful azure setup

### PR DESCRIPTION
**Pull request by Zeik0s**
These are the fixes i had to apply to get a working azure setup.

### CODE REVIEW

**Comment by Zeik0s** [comment]
fixes #863 #862 #860 and other Issues which i saw but haven't created an issue for.

**Comment by Zeik0s** [comment]
Still WIP.

**Comment by Zeik0s** [comment]
- [x] Splunk Contributor License Agreement signed

Azure setup is now in a working state based on this pull request
All Hosts successfully built, SOAR reworked to get it running on AlmaLinux instead of CentOS 
Importing of Cloud Logs and automated attacks not tested, but ansible playbooks ran through so this should be good to go. 

Rebased and force pushed so that only my commits are included in the history.

**Comment by P4T12ICK** [comment]
I will review your PR. Thank you for your submission. Sorry for the delay.

**Comment by P4T12ICK** [comment]
I can't use all the code because it breaks the aws version of Attack Range. But I will use part of it to improve it. I will close the PR and add the code manually. Thank you very much.

**Comment by Zeik0s** [comment]
Fair enough, thinking back it would have made sense, if i had split up the pull request for the multiple fixes i made. Still glad to see that some work is improving the upstream 😃

**Pull request closed without merging**
