### PR TITLE
Manually installing nginx on ubuntu 18.04

### PR DESCRIPTION
**Pull request by ljstella**
Now that key-value logging appears to be functional in open source NGINX, this PR reworks the nginx proxy server in AWS. Instead of using the AWS Marketplace image that costs $0.30/hour in software licensing fees, this installs OSS NGINX from the Ubuntu repositories. 

~TODO: Update configuration prompt to remove references to "NGINX Plus", testing newer version~

### CODE REVIEW

**Comment by ljstella** [comment]
Turns out, actually getting the config to take is important.

**Comment by ljstella** [comment]
Updating with a functional config.

**Comment by ljstella** [comment]
Screen Shot 2022-08-05 at 3 31 02 PM

Actually functional KV style logging on OSS nginx now.

**Comment by ljstella** [comment]
Removed references to "NGINX Plus" from configuration.py

**Review by P4T12ICK — APPROVED** [review]
Looks good to me

**Pull request merged**
