### PR TITLE
Add prelude support

### PR DESCRIPTION
**Pull request by josehelps**
This PR includes the following changes and features:

- [x] adds new configuration questions for prelude operator
- [x] add new configuration question for red team tools
- [x] updates readme replacing caldera with prelude
- [x] removes caldera 
- [x] adds pneuma agent installation for linux, windows base hosts, auto connects to prelude
- [x] adds improvement to dockerfile build process
- [x] adds a new prelude ansible role 

image

.. these machines have already been destroyed and creds are all temp 😄 
image

Identified Issues

- The prelude token is not being properly parsed and show back to the attack range user
- The documentation should better describe that the attack range user needs to download and run the Prelude client locally

### CODE REVIEW

**Review by mvelazc0 — APPROVED** [review]

**Comment by khyberspache** [comment]
Nice work @d1vious !! Just read through all the changes :)

**Comment by josehelps** [comment]
:ma

**Comment by mvelazc0** [comment]
Identified Issues

- The prelude token is not being properly parsed and show back to the attack range user
- The documentation should better describe that the attack range user needs to download and run the Prelude client locally

**Comment by josehelps** [comment]
modified the configure, and show flags to point to the guide https://github.com/splunk/attack_range/wiki/Prelude-Operator .. this should clarify the doc portion a bit, let me know what you think @mvelazc0

**Comment by mvelazc0** [comment]
tested it end to end, it works.

**Pull request merged**
