### PR TITLE
Implementation of search command over cli

### PR DESCRIPTION
**Pull request by P4T12ICK**
Changes:

1. search as a new action was implemented: Run a scheduled search from the command line
2. Bug: removed the pre task because it caused some problems. Changed the python environment to python3 for Ansible for the Ubuntu machine (which is in my opinion the cleaner solution)
3. put some of the code into modules: aws_service, splunk_sdk
4. ls is now defined as list searches
5. lm is now defined as list machines

### CODE REVIEW

**Comment by P4T12ICK** [comment]
And the lm (list machines) command contains now the IP addresses, if used with terraform. For vagrant they are anyway static.

**Comment by d1vious** [comment]
> And the lm (list machines) command contains now the IP addresses, if used with terraform. For vagrant they are anyway static.

We should probably still print them out, i have had scenarios where the vagrantfile needed to be modified because the network it used conflicted with the users local network. We can grab these out of the vagrant file.

**Comment by d1vious** [comment]
looks like the README.md needs to be updated to show listing search examples

**Comment by d1vious** [comment]
We should be able to handle the error when splunk is down 
```
┌──[jhernandez@jhernandez-mbp-cb9a8]─[~/splunk/attack_range on  search_command!]
└── # python attack_range.py -m vagrant -ls

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.

attack_range is using config at path attack_range.conf
2019-12-18 11:28:48,279 - INFO - attack_range - INIT - attack_range v1
Traceback (most recent call last):
  File "attack_range.py", line 401, in <module>
    list_all_searches(mode, settings, log)
  File "attack_range.py", line 302, in list_all_searches
    response = splunk_sdk.list_searches('localhost',str(settings['splunk_admin_password']))
  File "/Users/jhernandez/splunk/attack_range/modules/splunk_sdk.py", line 68, in list_searches
    password=splunk_password
  File "/Users/jhernandez/splunk/attack_range/venv/lib/python3.7/site-packages/splunklib/client.py", line 331, in connect
    s.login()
  File "/Users/jhernandez/splunk/attack_range/venv/lib/python3.7/site-packages/splunklib/binding.py", line 873, in login
    cookie="1") # In Splunk 6.2+, passing "cookie=1" will return the "set-cookie" header
  File "/Users/jhernandez/splunk/attack_range/venv/lib/python3.7/site-packages/splunklib/binding.py", line 1225, in post
    return self.request(url, message)
  File "/Users/jhernandez/splunk/attack_range/venv/lib/python3.7/site-packages/splunklib/binding.py", line 1242, in request
    response = self.handler(url, message, **kwargs)
  File "/Users/jhernandez/splunk/attack_range/venv/lib/python3.7/site-packages/splunklib/binding.py", line 1383, in request
    connection.request(method, path, body, head)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by P4T12ICK** [comment]
Improved additionally to the search command the following:

1. error handling for splunk is down
2. updated README
3. -lm for vagrant includes the IP addresses
4. new versions of TAs, ASX, ESCU
5. All index are part of default indexes -> searches can run without specifying an index=
6. Windows Server have an EIP (no IP address change between stop and resume)
7. some other bug fixing
8. new default password (changeme is quite insecure)

**Comment by d1vious** [comment]
Ran into a minor bug, not sure what is causing it yet, didn't notice anything obvious with the inputs files in Ansible. It seems when the files are copied the new line characters are not working in windows10 vagrant configuration. See the screenshot below:
https://imgur.com/OkxMDQS

**Comment by P4T12ICK** [comment]
This is related to notepad. If you open it with a proper editor, everything is fine. And the configuration is properly working.

**Pull request merged**
