### PR TITLE
moved default configuration to template

### PR DESCRIPTION
**Pull request by ghoto**
missing template

### CODE REVIEW

**Comment by d1vious** [comment]
Can you please update the attack_range.conf file with the latest notes to match that of the template, also we should update the installation guides and README.md to specifically dictate the fact that a user needs to copy the template conf over. But overall great idea thank you!

**Comment by ghoto** [comment]
@d1vious check it now.

**Comment by P4T12ICK** [comment]
I'm not sure if a template file improves the workflow from a developer perspective. Sanitizing the atttack_range.conf or the attack_range.conf.template is always needed before commiting to the project. But the new workflow adds another step for all the user and I can't see the benefit for the developer. When I develop a new feature with new parameters, then I still have to sanitize the parameter before copying them to the template (same risk of exposure of credentials as before). Furthermore, I think there is a big risk that a developer make some changes only at his own attack_range.conf file leading to a not working Attack Range. I'm used to use the -c flag with my own configuration.

**Comment by ghoto** [comment]
There are may reason to keep a .template file. I see using -c helps with a better development flow, indeed it should be encouraged in the README, instead of telling people to modify the `attack_range.conf` file (I just wonder how many of us are just using attack_range.conf). But having a default configuration that can run, and everybody sharing that default file, might cause that we accidentally leak information by overriding the default config, default passwords, etc.

I don't see what is the extra sanitation you need to do if the default changes are added to a file .template instead of a .conf. You still need to port your changes to your own .conf file. .template just prevent you to run default, unless you do an extra step (copy or update), and prevents you to push accidental changes to the repo unless you consciously add them to the right file.

**Pull request merged**
