### PR TITLE
Phantom Support

### PR DESCRIPTION
**Pull request by d1vious**
Adds Phantom Support to the Attack Range:

- [x] build a phantom server using mode terraform
- [x] build a phantom server using mode vagrant
- [x] build a phantom server using mode packer
- [x] configures Splunk and Phantom to communicate/share notables 
- [ ]  configures Splunk and Phantom to run searches from Phantom

### CODE REVIEW

**Comment by d1vious** [comment]
@philroyer-phantom I mistakenly merged: https://github.com/splunk/attack_range/pull/217 and @P4T12ICK made me aware it was not ready to be merged. I reverted this merge and re-opened the PR. Unfortunately all the commit messages went away but all the changes should have made it in here.

**Comment by P4T12ICK** [comment]
terraform, packer and vagrant are working. For the integration, there is still some parts missing.

**Comment by P4T12ICK** [comment]
The Phantom branch is ready. It's working with Packer, Vagrant and Terraform. You can send notables from Splunk to Phantom. The configuration of the Apps in Phantom is not yet done but I think we can do this in another iteration. Please review and merge.

**Comment by d1vious** [comment]
did some final testing, this looks ready to merge

**Pull request merged**
