### PR TITLE
Packer support

### PR DESCRIPTION
**Pull request by P4T12ICK**
New Features:
- Support of packer in order to speed up the build process
- Better documentation of attack-range.conf 

Wiki will be adapted after approving this merge request. For testing, make sure to install packer under /usr/local/bin/packer .

### CODE REVIEW

**Comment by P4T12ICK** [comment]
Added support for windows 10 ami

**Comment by d1vious** [comment]
Ran into a bug haven’t digged into it but seems like the `user_packer` variable might be missing from: https://github.com/splunk/attack_range/blob/packer_support/ansible/playbooks/windows_workstation_packer2.yml for example this playbook does have it https://github.com/splunk/attack_range/blob/packer_support/ansible/playbooks/windows_dc_client_packer2.yml#L9 

### error 

```
module.windows-client.aws_instance.windows_client_packer[0] (local-exec): TASK [windows_domain_client : pause] *******************************************
module.windows-client.aws_instance.windows_client_packer[0] (local-exec): fatal: [18.236.87.20]: FAILED! => {"msg": "The conditional check 'use_packer == \"1\"' failed. The error was: error while evaluating conditional (use_packer == \"1\"): 'use_packer' is undefined\n\nThe error appears to be in '/Users/jhernandez/splunk/attack_range/ansible/roles/windows_domain_client/tasks/create.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- pause:\n  ^ here\n"}

module.windows-client.aws_instance.windows_client_packer[0] (local-exec): NO MORE HOSTS LEFT *************************************************************

module.windows-client.aws_instance.windows_client_packer[0] (local-exec): PLAY RECAP *********************************************************************
module.windows-client.aws_instance.windows_client_packer[0] (local-exec): 18.236.87.20               : ok=4    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0



Error: Error running command 'ansible-playbook -i '18.236.87.20,' playbooks/windows_workstation_packer2.yml --extra-vars 'splunk_indexer_ip=10.0.1.5 ansible_user=Administrator ansible_password=I-l1ke-Attack-Range! win_password=I-l1ke-Attack-Range! splunk_uf_win_url=https://www.splunk.com/page/download_track?file=7.3.2/windows/splunkforwarder-7.3.2-c60db69f8e32-x64-release.msi&ac=&wget=true&name=wget&platform=Windows&architecture=x86_64&version=7.3.2&product=universalforwarder&typed=release win_sysmon_url=https://download.sysinternals.com/files/Sysmon.zip win_sysmon_template=SysmonConfig-TSwift.xml splunk_admin_password=I-l1ke-Attack-Range! windows_domain_controller_private_ip=10.0.1.6 windows_server_join_domain=1'': exit status 2. Output:
PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [18.236.87.20]

TASK [windows_domain_client : debug] *******************************************
ok: [18.236.87.20] => {
    "windows_server_join_domain": "1"
}

TASK [windows_domain_client : Change dns server to domain controller] **********
changed: [18.236.87.20]

TASK [windows_domain_client : reboot | Rebooting Server] ***********************
changed: [18.236.87.20]

TASK [windows_domain_client : pause] *******************************************
fatal: [18.236.87.20]: FAILED! => {"msg": "The conditional check 'use_packer == \"1\"' failed. The error was: error while evaluating conditional (use_packer == \"1\"): 'use_packer' is undefined\n\nThe error appears to be in '/Users/jhernandez/splunk/attack_range/ansible/roles/windows_domain_client/tasks/create.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- pause:\n  ^ here\n"}
```

Also I was wondering why there are two versions of each playbook, should we clean up their names if it was something just left over from testing?

**Comment by P4T12ICK** [comment]
Good finding. I will fix that. 

We need two versions of each playbook because the playbooks needs to be split up into two playbooks: One playbook which runs through provisioning with packer and another one which runs afterwards. Maybe the naming of the playbooks could be better.

**Comment by P4T12ICK** [comment]
The bug is fixed.

**Pull request merged**
